Company: Hindsight
Application: Coauthor
ProductDescription: some description
Market:
  - UK
SoftwareClassification:
  Questions:
    HazardousSituationPossible: false
  SafetyClass: A
  Rationale: some text
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatibilityTesting:
    - BrowserStack
    - SauceLabs
Roles:
  Management:
    Lead: michelle
    Members:
      - mike
      - molly
      - michelle
  SWDevelopment:
    Lead: sam
    Members:
      - sam
      - sally
      - susan
  Clinical:
    Lead: cathy
    Members:
      - github-org/cathy-christy-team
      - carl
  QARA:
    Lead: romeo
    Members:
      - rosy
      - 'github-org/rosy-romeo-team'
SDLC:
  BranchingStrategy: "Feature Branching"
  CommitMessageFormat: "Conventional Commits"
  Methodology: "SCRUM"
  IterationLength: 2
RequirementManagement:
  GitHub:
      ProjectLink: https://github.com/orgs/company-org/projects/2
Security:
  CommitSigning: true
  PenetrationTesting:
    Required: true
    Frequency: "Quarterly"
  SAST:
    Tools:
      - "SonarQube"
      - "Checkmarx"
    Frequency: "Every Build"
  SBOM:
    GenerationTools:
      - "WhiteSource"
      - "BlackDuck"
    MonitoringTools:
      - "WhiteSource"
      - "BlackDuck"
    Frequency: "Every Build"
