Company: aparkinson
Application: Coauthor
ProductDescription: |
  Product Description Line 1
  Product Description Line 2
Market:
  - UK
SoftwareClassification:
  Questions:
    HazardousSituationPossible: false
  SafetyClass: A
  Rationale: |
    This is a class A rationale
    This is a class A rationale
TestingTools:
  SystemTesting:
    - Selenium
    - Cypress
    - Cucumber
  SecurityTesting:
    - ZAP
    - Burp
  CompatabilityTesting:
    - BrowserStack
    - SauceLabs
BugTrackingProjectLink: replace-me-with-bug-tracking-project-link
Roles:
  # Please add/change GitHub usernames to the following roles
  Management:
    Lead: aparkinson
    Members:
      - aparkinson
  SWDevelopment:
    Lead: aparkinson
    Members:
      - aparkinson
  Clinical:
    Lead: aparkinson
    Members:
      - aparkinson
  QARA:
    Lead: aparkinson
    Members:
      - aparkinson
